---
title: "Untitled"
author: "Jeff Nieman"
date: "April 11, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Final Project - begin with uploading file into R




```{r}
vehicles <- read.csv("C:/Users/Jeffrey Nieman/Documents/CUNY/Data 608/HW/vehicles.csv", strip.white = TRUE)

require(dplyr)

#reduce to standard cylinders (4,6,8) to eliminate outliers...

veh_clean <- filter(vehicles,cylinders == 4 | cylinders == 6 | cylinders == 8)

veh_clean$trany <- as.character(veh_clean$trany)
veh_clean$drive <- as.character(veh_clean$drive)

#create meaningful vehicle class to allow us to better track trends

veh_clean$Class <- as.character(veh_clean$VClass)
veh_clean$Class[which(veh_clean$Class == 'Compact Cars')] <- 'Compact'
veh_clean$Class[which(veh_clean$Class == 'Large Cars')] <- 'Large'
veh_clean$Class[which(veh_clean$Class == 'Midsize Cars')] <- 'Midsize'
veh_clean$Class[which(veh_clean$Class == 'Compact Cars')] <- 'Compact'
veh_clean$Class[which(veh_clean$Class == 'Midsize Station Wagons')] <- 'Wagon' 
veh_clean$Class[which(veh_clean$Class == 'Midsize-Large Station Wagons')] <- 'Wagon'
veh_clean$Class[which(veh_clean$Class == 'Minicompact Cars')] <- 'Compact'
veh_clean$Class[which(veh_clean$Class == 'Minivan - 2WD')] <- 'Van'
veh_clean$Class[which(veh_clean$Class == 'Minivan - 4WD')] <- 'Van'
veh_clean$Class[which(veh_clean$Class == 'Small Pickup Trucks')] <- 'Truck'
veh_clean$Class[which(veh_clean$Class == 'Small Pickup Trucks 2WD')] <- 'Truck'
veh_clean$Class[which(veh_clean$Class == 'Small Pickup Trucks 4WD')] <- 'Truck'
veh_clean$Class[which(veh_clean$Class == 'Small Sport Utility Vehicle 2WD')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Small Sport Utility Vehicle 4WD')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Small Station Wagons')] <- 'Wagon'
veh_clean$Class[which(veh_clean$Class == 'Special Purpose Vehicle')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Special Purpose Vehicle 2WD')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Special Purpose Vehicle 4WD')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Special Purpose Vehicles')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Special Purpose Vehicles/2wd')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Special Purpose Vehicles/4wd')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Sport Utility Vehicle - 2WD')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Sport Utility Vehicle - 4WD')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Standard Pickup Trucks')] <- 'Truck'
veh_clean$Class[which(veh_clean$Class == 'Standard Pickup Trucks 2WD')] <- 'Truck'
veh_clean$Class[which(veh_clean$Class == 'Standard Pickup Trucks 4WD')] <- 'Truck'
veh_clean$Class[which(veh_clean$Class == 'Standard Pickup Trucks/2wd')] <- 'Truck'
veh_clean$Class[which(veh_clean$Class == 'Standard Sport Utility Vehicle 2WD')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Standard Sport Utility Vehicle 4WD')] <- 'SUV'
veh_clean$Class[which(veh_clean$Class == 'Subcompact Cars')] <- 'Compact'
veh_clean$Class[which(veh_clean$Class == 'Two Seaters')] <- 'Compact'
veh_clean$Class[which(veh_clean$Class == 'Vans')] <- 'Van'
veh_clean$Class[which(veh_clean$Class == 'Vans, Cargo Type')] <- 'Van'
veh_clean$Class[which(veh_clean$Class == 'Vans, Passenger Type')] <- 'Van'
veh_clean$Class[which(veh_clean$Class == 'Vans Passenger')] <- 'Van'

##Clean the transmission data
veh_clean$trans <- veh_clean$trany
veh_clean$trans[which(veh_clean$trans == 'Auto(AM-S6)')] <- 'Automatic 6 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (A1)')] <- 'Automatic Other'
veh_clean$trans[which(veh_clean$trans == 'Automatic (AM6)')] <- 'Automatic 6 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (AM7)')] <- 'Automatic 7 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (AM8)')] <- 'Automatic 8 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (AM-S6)')] <- 'Automatic 6 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (AM-S7)')] <- 'Automatic 7 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (AM-S8)')] <- 'Automatic 8 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (AM-S9)')] <- 'Automatic Other'
veh_clean$trans[which(veh_clean$trans == 'Automatic (AV-S6)')] <- 'Automatic 6 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (AV-S7)')] <- 'Automatic 7 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (AV-S8)')] <- 'Automatic 8 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (L3)')] <- 'Automatic 3 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (L4)')] <- 'Automatic 4 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (S10)')] <- 'Automatic Other'
veh_clean$trans[which(veh_clean$trans == 'Automatic (S4)')] <- 'Automatic 4 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (S5)')] <- 'Automatic 5 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (S6)')] <- 'Automatic 6 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (S7)')] <- 'Automatic 7 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (S8)')] <- 'Automatic 8 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic (S9)')] <- 'Automatic Other'
veh_clean$trans[which(veh_clean$trans == 'Automatic (variable gear ratios)')] <- 'Automatic Other'
veh_clean$trans[which(veh_clean$trans == 'Automatic 3-spd')] <- 'Automatic 3 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic 4-spd')] <- 'Automatic 4 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic 5-spd')] <- 'Automatic 5 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic 6-spd')] <- 'Automatic 6 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic 7-spd')] <- 'Automatic 7 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic 8-spd')] <- 'Automatic 8 Speed'
veh_clean$trans[which(veh_clean$trans == 'Automatic 9-spd')] <- 'Automatic Other'
veh_clean$trans[which(veh_clean$trans == 'Manual 3-spd')] <- 'Manual 3 Speed'
veh_clean$trans[which(veh_clean$trans == 'Manual 4-spd')] <- 'Manual 4 Speed'
veh_clean$trans[which(veh_clean$trans == 'Manual 4-spd Doubled')] <- 'Manual 4 Speed'
veh_clean$trans[which(veh_clean$trans == 'Manual 5-spd')] <- 'Manual 5 Speed'
veh_clean$trans[which(veh_clean$trans == 'Manual 6-spd')] <- 'Manual 6 Speed'
veh_clean$trans[which(veh_clean$trans == 'Manual 7-spd')] <- 'Manual 7 Speed'
veh_clean$trans[which(veh_clean$trans == ' ')] <- 'Automatic Other'


#write to csv the cleaned data
write.csv(veh_clean, file="vehicles_cleaned.csv")
#Test to see which factors are most relevant using simple lm


veh_clean2 <- veh_clean[,c(16,23:25,64,84,85)]

write.csv(veh_clean2, file="vehicles_cleaned2.csv")
veh_trend <- glm(data=veh_clean2, comb08~.)
summary(veh_trend)


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
